<template>
  <form class="search-form mod">
    <div class="holder">
      <fieldset class="search-form_search-holder cf">
        <InputElement
          label="full name"
          inputId="name"
          inputName="name"
          inputType="text"
          placeholder="Search by name"
          class="search-form_search-input float-left"
          :hideLabel="true"
          :triggerValidation="triggerValidation"
          :resetInput="resetFormPrimary"
          :resetValidationObj="resetValidationFormPrimary"
          @emittedErrorInput="handleErrorInput"
          @emittedValidInput="handleValidInput"
        />
        <button
          type="button"
          class="cta search-form_fix-width-cta float-right"
          @click="handleClickSearchCta"
        >
          Search
        </button>
        <button
          type="button"
          class="cta search-form_fix-width-cta float-right"
          @click="handleClickResetFormCta"
        >
          Reset
        </button>
      </fieldset>
      <div class="search-form_separator"></div>
      <fieldset class="search-form_filters">
        <h2 class="sub-title">Filters</h2>
        <div v-if="getYearSliderObj">
          <p class="sub-title sub-title-xs">Age range</p>
          <vue-slider
            v-model="sliderArray"
            :enable-cross="false"
            class="input-element_slider"
          />
        </div>
        <div v-if="getGenderRadioBoxObj">
          <p class="sub-title sub-title-xs">By gender</p>
          <RadioGroup
            inputName="gender"
            :checkBoxes="getGenderRadioBoxObj"
            :triggerValidation="triggerValidationSecodnary"
            :resetInput="resetFormSecondary"
            @emittedErrorInput="handleErrorInput"
            @emittedValidInput="handleValidInput"
          />
        </div>
        <div v-if="getEyeCheckBoxObj">
          <p class="sub-title sub-title-xs">By eye color</p>
          <CheckboxGroup
            inputName="eye-color"
            :checkBoxes="getEyeCheckBoxObj"
            :triggerValidation="triggerValidationSecodnary"
            :resetInput="resetFormSecondary"
            @emittedErrorInput="handleErrorInput"
            @emittedValidInput="handleValidInput"
          />
        </div>
        <div v-if="getPetCheckBoxObj">
          <p class="sub-title sub-title-xs">By prefered animal</p>
          <CheckboxGroup
            inputName="prefered-pet"
            :checkBoxes="getPetCheckBoxObj"
            :triggerValidation="triggerValidationSecodnary"
            :resetInput="resetFormSecondary"
            @emittedErrorInput="handleErrorInput"
            @emittedValidInput="handleValidInput"
          />
        </div>
        <div v-if="getFruitCheckBoxObj">
          <p class="sub-title sub-title-xs">By prefered fruit</p>
          <CheckboxGroup
            inputName="prefered-fruit"
            :checkBoxes="getFruitCheckBoxObj"
            :triggerValidation="triggerValidationSecodnary"
            :resetInput="resetFormSecondary"
            @emittedErrorInput="handleErrorInput"
            @emittedValidInput="handleValidInput"
          />
        </div>
      </fieldset>
    </div>
  </form>
</template>

<script>
import "../scss/components/search-form.scss";

import VueSlider from "vue-slider-component";
import flushPromises from "flush-promises";
import { mapGetters, mapActions } from "vuex";
import helpers from "../helpers/jsData";

import InputElement from "./InputElement.vue";
import RadioGroup from "./RadioGroup.vue";
import CheckboxGroup from "./CheckboxGroup.vue";

export default {
  name: "SearchForm",
  components: {
    InputElement,
    RadioGroup,
    CheckboxGroup,
    VueSlider
  },
  data() {
    return {
      sliderTimer: {}, // timer for slider update
      formErrorState: [], // holds the errors generated by the form
      sliderArray: [0, 100], // slider size
      triggerValidation: 0, // trigger the form validation
      triggerValidationSecodnary: 0, // prevent validation for some inputs
      resetFormPrimary: 0, // reset part of the form
      resetFormSecondary: 0, // reset part of the form
      resetValidationFormPrimary: 0, // reset the valdiation msg for the first fieldset
      allowFormValidation: true, // allow form validation flag
      allowAgeFilterUpdate: false, // allow filter age store update flag
      triggerFiltering: 0 // triggers the list filtering assign to this form
    };
  },
  computed: {
    ...mapGetters("searchForm", [
      "getFilters",
      "getGenderRadioBoxObj",
      "getEyeCheckBoxObj",
      "getPetCheckBoxObj",
      "getFruitCheckBoxObj",
      "getYearSliderObj"
    ])
  },
  watch: {
    sliderArray() {
      // if the form has been reset don't update the store
      if (this.allowAgeFilterUpdate) {
        clearTimeout(this.sliderTimer);
        this.sliderTimer = setTimeout(() => {
          this.setFiltersInStore({ name: "age", value: this.sliderArray });
        }, helpers.timers.fast);
      } else {
        this.setAllowAgeFilterUpdate(true);
      }
    },
    getYearSliderObj() {
      this.sliderArray = this.getYearSliderObj;
    }
  },
  methods: {
    // actions form searchForm module vuex file
    ...mapActions("searchForm", [
      "setFilters",
      "setResetFilters",
      "setTriggerFiltering"
    ]),
    // checks if the user has set filters
    checkUserSetFilters() {
      const filters = this.getFilters,
        filtersKeys = Object.keys(filters);

      for (let x = 0; x < filtersKeys.length; x++) {
        const key = filtersKeys[x];

        if (key === "name") continue;

        if (Array.isArray(filters[key]) && filters[key].length) {
          this.setAllowFormValidation(false);
        } else if (typeof filters[key] === "string" && filters[key]) {
          this.setAllowFormValidation(false);
        }
      }
    },
    // stops the watcher to update the store
    setAllowAgeFilterUpdate(value) {
      this.allowAgeFilterUpdate = value;
    },
    // stores the errors fro the form
    setFormError(obj) {
      this.formErrorState.push(obj);
    },
    incrementFilterTriggering() {
      this.triggerFiltering += 1;
    },
    // wrapper method around the store setFilters action
    setFiltersInStore(obj) {
      const filters = this.getFilters;

      filters[obj.name] = obj.value;
      this.resetValidationFormPrimaryMethod();
      this.setFilters(filters);
    },
    // resets the form errors array
    resetFormErrors() {
      this.formErrorState = [];
    },
    // resets the slider
    resetSlider() {
      this.sliderArray = this.getYearSliderObj;
    },
    // deals with the errors emitted by the inputs
    handleErrorInput(obj) {
      // store the value
      this.setFormError(obj);
    },
    // deals with the data
    handleValidInput(obj) {
      this.setFiltersInStore(obj);
    },
    // setter for the allowFormValidation flag
    setAllowFormValidation(value) {
      this.allowFormValidation = value;
    },
    // triggers a form validation for inputs
    validateForm() {
      this.triggerValidation += 1;
    },
    async handleClickSearchCta() {
      this.resetFormErrors();
      this.setAllowFormValidation(true);
      this.checkUserSetFilters();

      if (this.allowFormValidation) this.validateForm();

      await flushPromises();

      // if form passes validation
      if (this.formErrorState.length === 0) {
        this.incrementFilterTriggering();
        this.setTriggerFiltering(this.triggerFiltering);
      }
    },
    resetValidationFormPrimaryMethod() {
      this.resetValidationFormPrimary += 1;
    },
    // reset the form state and hides errors
    resetAllFormState() {
      this.resetFormPrimary += 1;
      this.resetFormSecondary += 1;

      this.setAllowFormValidation(true);
    },
    // reset the form state
    handleClickResetFormCta() {
      this.resetAllFormState();
      this.resetSlider();

      // action from vuex
      this.setResetFilters();
      this.setAllowAgeFilterUpdate(false);
    }
  }
};
</script>
